{% set name = "pygamma_n" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://currents.soest.hawaii.edu/hgstage/pygamma/archive/v{{ version }}.tar.gz
  sha256: 2faaedae997d18a842e0786361c0ec79d5f5cfb0736810d17a18275b31965b1b

build:
  number: 0
  skip: true  # [py<39 or win]
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}  # [not win]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - numpy >=2
    - meson-python
    - netcdf-fortran
    - setuptools_scm
  run:
    - python
    - netcdf-fortran
    - numpy

test:
  source_files:
    - pygamma_n/tests/
  requires:
   - pytest
   - pip
  imports:
    - pygamma_n
  commands:
    - pip check
    - pytest pygamma_n/tests/

about:
  home: https://currents.soest.hawaii.edu/hgstage/pygamma
  license: MIT AND LicenseRef-CSIRO
  license_file: pygamma_n/src/ConditionsOfUse
  summary: Python interface for the original Fortran neutral density

extra:
  recipe-maintainers:
    - ocefpaf
    - efiring
